# Generated by Django 2.2.7 on 2020-10-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_auto_20201018_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
